project/models/Printer.py
# -*- coding: utf-8 -*-
from flask import flash


class Printer(object):

    def show_string(self, text):
        if text == '':
            flash("You didn't enter any text to flash")
        else:
            flash(text + "!!!")

project/controllers/admin/controllers.py
# -*- coding: utf-8 -*-
from flask import render_template, request
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired
from flask import Blueprint
from project.models.Printer import Printer


admin = Blueprint('admin', __name__)


class CreateForm(FlaskForm):
    text = StringField('name', validators=[DataRequired()])


@admin.route('/', methods=['GET', 'POST'])
def printer():
    form = CreateForm(request.form)
    if request.method == 'POST' and form.validate():
        printer = Printer()
        printer.show_string(form.text.data)
        return render_template('printer/index.html')
    return render_template('printer/print.html', form=form)

project/controllers/main/controllers.py
# -*- coding: utf-8 -*-
from flask import render_template
from flask import Blueprint


main = Blueprint('main', __name__)


@main.route('/')
def start():
    return render_template('printer/index.html')

project/templates/layout/layout.html
<!doctype html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        <title>Flask-MVC</title>
    </head>
    <body>
        <a style="text-align:center" href="{{ url_for('admin.printer') }}">Home</a>
        <a style="text-align:center" href="http://ratapp.co.ke">About</a>
        <div class="page">
            <h1>Flask MVC Boilerplate</h1>
            {% for message in get_flashed_messages() %}
                <div class="flash">{{ message }}</div>
            {% endfor %}
            {% macro render_error(field) %}
                {% if field.errors %}
                    {% for error in field.errors %}<span class='error'>{{ error }}</span>{% endfor %}
                {% endif %}
            {% endmacro %}
            {% block body %}{% endblock %}
        </div>
    </body>
</html>

project/templates/printer/index.html
{% extends "layout/layout.html" %}
{% block body %}
    <ul> 
        <p>
            <a href="{{ url_for('admin.printer') }}">Click here to print!</a>
        </p>
    </ul>
{% endblock %}

project/templates/printer/print.html
{% extends "layout/layout.html" %}
{% block body %}
    <form action="{{ url_for('admin.printer') }}" method="post">
        {{ form.csrf_token }}
        <dl>
            <dd>{{ form.text.label }} {{ form.text(size=20) }} {{ render_error(form.text) }}</dd>
            <dd><input type="submit" value="Flash"/></dd>
        </dl>
    </form>
{% endblock %}